"""Added all tables

Revision ID: 91806808b4bd
Revises: 
Create Date: 2026-08-20 23:10:40.346044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91806808b4bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('account_tier', sa.String(), nullable=False),
    sa.Column('sla', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_name'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='Admin', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_tier', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('unified_ticket', sa.String(), nullable=True),
    sa.Column('telemetry_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('extracted_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('search_query', sa.String(), nullable=True),
    sa.Column('retrieved_docs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eval_confidence', sa.Float(), nullable=True),
    sa.Column('has_hallucinations', sa.Boolean(), nullable=True),
    sa.Column('grounding_source_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('eval_feedback', sa.String(), nullable=True),
    sa.Column('ai_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('human_decision', sa.String(), nullable=True),
    sa.Column('human_edited_text', sa.String(), nullable=True),
    sa.Column('final_response_text', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback_comment', sa.String(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('troubleshooting_steps', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_thread_id'), 'tickets', ['thread_id'], unique=True)
    op.create_table('ticket_diffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('change_type', sa.VARCHAR(), nullable=True),
    sa.Column('target_entity', sa.VARCHAR(), nullable=True),
    sa.Column('old_value', sa.VARCHAR(), nullable=True),
    sa.Column('new_value', sa.VARCHAR(), nullable=True),
    sa.Column('factual_correction', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['admins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_diffs')
    op.drop_index(op.f('ix_tickets_thread_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('admins')
    op.drop_table('accounts')
    # ### end Alembic commands ###
