from typing import Any
from pydantic import BaseModel, Field


# Ticket creation payload

class CreateTicketRequest(BaseModel):
    subject: str = Field(
        description="Original subject submitted by user.",
    )

    body: str = Field(
        description="Original description body submitted by user.",
    )


# Qwen node output

class QwenOutput(BaseModel):
    has_image: bool = Field(
        default=False,
        description="Checks if image is included in the ticket context.",
    )

    image: str | None = Field(
        default=None,
        description="First ticket image.",
    )

    images: list[str] = Field(
        default_factory=list,
        description="Ticket image URLs or data URLs.",
    )

    image_text: str = Field(
        default="",
        description="Extracted text from image or OCR model.",
    )


# DistilBERT node output

class DistilbertOutput(BaseModel):
    department: str = Field(
        description="Target routing department.",
    )

    confidence: float = Field(
        description="Classification confidence score from DistilBERT.",
    )

    unified_ticket: str = Field(
        description="Merged and cleaned text combining subject, body, and OCR text.",
    )

    telemetry_data: dict[str, Any] | None = Field(
        default=None,
        description="Parsed metadata, log snippets, or system metrics.",
    )


# Business context

class TicketContext(BaseModel):
    account_tier: str = Field(
        default="Standard",
        description="SLA/account priority tier such as Solo, Team, or Enterprise.",
    )


# Llama triager node output

class LlamaOutput(BaseModel):
    search_query: str = Field(
        default="",
        description="Active search query generated by Node 1 for RAG retrieval.",
    )

    priority: str = Field(
        description="Inferred ticket urgency such as Low, Medium, High, or Critical.",
    )

    tags: list[str] = Field(
        default_factory=list,
        description="Categorization tags generated by Llama.",
    )

    extracted_keywords: list[str] = Field(
        default_factory=list,
        description="Key technical terms, error codes, and tokens extracted for search.",
    )


# Base ticket response

class BaseResponse(BaseModel):
    id: int = Field(
        description="Unique system database record ID.",
    )

    user_id: int = Field(
        description="User account identifier.",
    )

    email: str = Field(
        description="User account email.",
    )

    subject: str = Field(
        description="Root ticket subject.",
    )

    body: str = Field(
        description="Root ticket description.",
    )

    status: str = Field(
        description="Current workflow lifecycle status.",
    )

    latency: float = Field(
        description="Total end-to-end processing pipeline execution time in seconds.",
    )


# Semantic documentation difference

class SemanticDiff(BaseModel):
    factual_correction: str | None = Field(
        default=None,
        description=(
            "A concise explanation detailing why the modification was made, "
            "focusing on correcting a hallucination, inaccurate information, "
            "or out-of-date information."
        ),
    )

    target_entity: str | None = Field(
        default=None,
        description=(
            "The precise keyword, phrase, variable name, or customer identity "
            "parameter within the document context that is being modified."
        ),
    )

    old_value: str | None = Field(
        default=None,
        description=(
            "The original, uncorrected, or outdated text/value as it appeared "
            "before the modification."
        ),
    )

    new_value: str | None = Field(
        default=None,
        description=(
            "The updated, accurate, or corrected text/value that replaces "
            "the previous data."
        ),
    )

    change_type: str | None = Field(
        default="TONE_ONLY",
        description=(
            "Categorizes the nature of the change. Use TONE_ONLY if the "
            "underlying facts remain identical and only the voice, empathy, "
            "grammar, wording, or formatting changed. Use FACTUAL if a "
            "factual value, status, instruction, or technical meaning changed."
        ),
    )


# Documentation drift

class Drift(BaseModel):
    target_entity: str | None = Field(
        default=None,
        description=(
            "The precise keyword, phrase, variable name, or technical entity "
            "that was repeatedly corrected."
        ),
    )

    old_value: str | None = Field(
        default=None,
        description=(
            "The original value that appeared before the repeated correction."
        ),
    )

    new_value: str | None = Field(
        default=None,
        description=(
            "The corrected value that multiple agents independently used."
        ),
    )

    agent_count: int = Field(
        description=(
            "The number of distinct support agents who made this exact "
            "correction within the detection window."
        ),
    )


class AllDrift(BaseModel):
    drift_detected: bool = Field(
        default=False,
        description="Whether a documentation drift pattern was detected.",
    )

    all_drifts: list[Drift] = Field(
        default_factory=list,
        description="All detected documentation drift patterns.",
    )


class DriftAlert(BaseModel):
    target_entity: str | None = Field(
        default=None,
        description="The entity that was repeatedly corrected.",
    )

    old_value: str | None = Field(
        default=None,
        description="The original value before the repeated correction.",
    )

    new_value: str | None = Field(
        default=None,
        description="The corrected value used by the support agents.",
    )

    agent_count: int = Field(
        default=0,
        description="Number of distinct agents who made the same correction.",
    )

    message: str = Field(
        description=(
            "A concise human-readable documentation drift alert describing "
            "the repeated correction."
        ),
    )


# Engineer solution

class EngineerSolution(BaseModel):
    troubleshooting_steps: str
    root_cause: str
    solution: str
    engineer_id: int


# Ticket reward
class TicketReward(BaseModel):
    user_rating: int = Field(..., ge=1, le=5)
    user_feedback: str = Field(..., min_length=1, max_length=2000)
    
class ResolvedTicket(BaseModel):
    ticket_id: int
    resolution: str = Field(..., min_length=1)
    edited: bool = False
