from datetime import datetime
from typing import Any

import sys
import types

from pydantic import BaseModel, Field


# Keep checkpoints written by the previous ``app.agents.state`` layout readable.
_legacy_app = sys.modules.setdefault("app", types.ModuleType("app"))
_legacy_app.__path__ = []
_legacy_agents = sys.modules[__package__]
setattr(_legacy_app, "agents", _legacy_agents)
sys.modules.setdefault("app.agents", _legacy_agents)
sys.modules.setdefault("app.agents.state", sys.modules[__name__])


class RagState(BaseModel):
    document_id: str = Field(
        description="Unique identifier for the retrieved chunk/document."
    )
    document_score: float = Field(
        description="Relevance or similarity score computed during retrieval."
    )
    document_content: str = Field(
        description="Text content of the retrieved document."
    )


class EvaluationResult(BaseModel):
    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 and 1.0 evaluating how accurately the docs resolve the ticket.",
    )
    has_hallucinations: bool = Field(
        description="True if the draft answer or retrieved context contains ungrounded claims."
    )
    grounding_source_ids: list[str] = Field(
        default_factory=list,
        description="List of document_ids from retrieved_docs that directly support the resolution.",
    )
    feedback_for_rewriter: str | None = Field(
        default=None,
        description="Actionable query-refinement instructions for Node 1 if confidence_score < 0.7.",
    )


class AIDraftResolution(BaseModel):
    greeting: str = Field(
        description="Personalized greeting using customer name or tier context."
    )
    issue_summary: str = Field(
        description="Brief confirmataion of the customer's technical problem."
    )
    root_cause: str = Field(
        description="Clear explanation of why the issue occurred."
    )
    resolution_steps: list[str] = Field(
        description="Number-by-number actionable steps for the customer."
    )
    closing: str = Field(
        description="Support sign-off and follow-up guidance."
    )
    full_response_text: str = Field(
        description="The complete assembled email/message ready to send to the customer."
    )


class HumanReviewPayload(BaseModel):
    question: str = Field(
        default="Do you approve sending this response to the customer?"
    )

    ticket_id: int
    user_id: int
    account_tier: str
    priority: str
    department: str
    subject: str
    original_body: str
    telemetry_data: dict[str, Any] | None = None

    confidence_score: float
    has_hallucinations: bool
    grounding_source_ids: list[str]
    retrieved_docs: list[dict[str, Any]]

    ai_draft: AIDraftResolution


class GraphState(BaseModel):
    # Original ticket input
    id: int | None = Field(
        default=None,
        description="Unique system database record ID.",
    )
    user_id: int | None = Field(
        default=None,
        description="User account identifier.",
    )
    email: str = Field(
        default="",
        description="User account email.",
    )
    subject: str = Field(
        default="",
        description="Original ticket subject.",
    )
    body: str = Field(
        default="",
        description="Original ticket description.",
    )
    # Image and OCR state
    has_image: bool = Field(
        default=False,
        description="Checks if image is included in the ticket context.",
    )
    image: str | None = Field(
        default=None,
        description="First ticket image, retained for backward compatibility.",
    )
    images: list[str] = Field(
        default_factory=list,
        description="Ticket image URLs or data URLs.",
    )
    image_text: str = Field(
        default="",
        description="Extracted text from image or OCR model.",
    )

    # DistilBERT classification state
    department: str | None = Field(
        default=None,
        description="Target routing department produced by DistilBERT.",
    )
    confidence: float | None = Field(
        default=None,
        description="Classification confidence score from DistilBERT.",
    )
    unified_ticket: str | None = Field(
        default=None,
        description="Merged and cleaned ticket text.",
    )

    # Production telemetry
    telemetry_data: dict[str, Any] | None = Field(
        default=None,
        description="Parsed metadata, log snippets, or system metrics.",
    )

    # Business context
    account_tier: str = Field(
        default="Standard",
        description="SLA/account priority tier such as Solo, Team, or Enterprise.",
    )

    # Llama triage state
    search_query: str | None = Field(
        default=None,
        description="Active search query generated by the triage node.",
    )
    priority: str | None = Field(
        default=None,
        description="Inferred ticket urgency.",
    )
    tags: list[str] = Field(
        default_factory=list,
        description="Categorization tags generated by Llama.",
    )
    extracted_keywords: list[str] = Field(
        default_factory=list,
        description="Key technical terms extracted for search.",
    )

    # Workflow state
    status: str = Field(
        default="Pending",
        description="Current workflow lifecycle status.",
    )
    latency: float = Field(
        default=0.0,
        description="Total end-to-end processing pipeline execution time in seconds.",
    )

    # Search and retrieval state
    retrieved_docs: list[RagState] = Field(
        default_factory=list,
        description="Documents retrieved through hybrid search.",
    )

    # Retry and query refinement state
    retries: int = Field(
        default=0,
        description="Number of RAG query attempts.",
    )
    rag_query_feedback: str | None = Field(
        default=None,
        description="Latest feedback from the evaluator.",
    )
    rag_query_feedback_list: list[str] = Field(
        default_factory=list,
        description="History of query-refinement feedback.",
    )

    # Evaluation state
    eval_result: EvaluationResult | None = Field(
        default=None,
        description="Structured output returned by the evaluator.",
    )

    # Resolution state
    ai_draft: AIDraftResolution | None = Field(
        default=None,
        description="Generated AI resolution.",
    )
    human_decision: str | None = Field(
        default=None,
        description="Decision made during human review.",
    )
    final_response_text: str | None = Field(
        default=None,
        description="Final response sent to the customer.",
    )

    # Delivery state
    email_sent: bool = Field(
        default=False,
        description="Whether the final response was sent.",
    )
    message_id: str | None = Field(
        default=None,
        description="Message or email ID after sending.",
    )

    # Escalation state
    escalation_message: str | None = Field(
        default=None,
        description="Response from escalating the ticket to Jira.",
    )


class ApprovalDecision(BaseModel):
    decision: str
    edited_text: str | None = None
    department: str | None = None


class UserTicketResponse(GraphState):
    created_at: datetime
